'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),{Server}=require('socket.io'),{io:client}=require('socket.io-client'),install=require('../duo-server');
function event(s,name,pred=()=>true){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{s.off(name,fn);reject(Error(name+' timeout'));},2500);function fn(d){if(pred(d)){clearTimeout(timer);s.off(name,fn);resolve(d);}}s.on(name,fn);});}
async function setup(t,opts={}){const server=http.createServer(),io=new Server(server),engine=install(io,{roundMs:10000,reviewMs:10000,grace:200,leadMs:20,...opts});await new Promise(r=>server.listen(0,'127.0.0.1',r));const clients=[];t.after(async()=>{clients.forEach(s=>s.disconnect());engine.close();await new Promise(r=>io.close(r));});async function connect(){const s=client(`http://127.0.0.1:${server.address().port}/duo`,{transports:['websocket'],forceNew:true,reconnection:false});clients.push(s);await event(s,'connect');return s;}return{connect,engine};}
async function room(connect,game){const a=await connect(),b=await connect();let wait=event(a,'session');a.emit('create',{game,name:'A',count:5});const session=await wait;wait=event(b,'state');b.emit('join',{code:session.code,name:'B'});await wait;const wa=event(a,'state',d=>d.phase==='round'),wb=event(b,'state',d=>d.phase==='round');a.emit('start',{});return{a,b,session,sa:await wa,sb:await wb};}
test('taboo protects secret, rejects banned clue, accepts answer, alternates roles',async t=>{const {connect}=await setup(t);const {a,b,sa,sb}=await room(connect,'taboo');assert.equal(sa.item.role,'explain');assert.equal(sb.item.role,'guess');assert.equal(sb.item.word,undefined);assert.equal(sb.item.banned,undefined);let wait=event(a,'error-message');a.emit('chat',{roundKey:sa.roundKey,text:sa.item.word});await wait;wait=event(b,'state',d=>d.messages.length===1);a.emit('chat',{roundKey:sa.roundKey,text:'이것을 보고 생각해 보세요'});await wait;wait=event(a,'state',d=>d.phase==='review');b.emit('chat',{roundKey:sa.roundKey,text:sa.item.word});const result=await wait;assert.ok(result.result.results.every(x=>x.points===100));wait=event(a,'state',d=>d.phase==='round'&&d.round===2);a.emit('ready',{roundKey:sa.roundKey});b.emit('ready',{roundKey:sa.roundKey});assert.equal((await wait).item.role,'guess');});
test('telepathy reveals only after both responses, scores predictions, locks duplicate and stale inputs',async t=>{const {connect}=await setup(t),{a,b,sa}=await room(connect,'telepathy');let wait=event(a,'state',d=>d.submitted);a.emit('answer',{roundKey:sa.roundKey,own:0,predict:2});const locked=await wait;assert.equal(locked.result,null);a.emit('answer',{roundKey:sa.roundKey,own:1,predict:1});wait=event(a,'state',d=>d.phase==='review');b.emit('answer',{roundKey:sa.roundKey,own:2,predict:0});assert.ok((await wait).result.results.every(x=>x.points===100));});
test('timing ignores claimed elapsed time and rejects pressing before start',async t=>{const {connect,engine}=await setup(t,{leadMs:100}),{a,b,sa}=await room(connect,'timing');let wait=event(a,'error-message');a.emit('answer',{roundKey:sa.roundKey,elapsed:sa.item.target});await wait;const r=engine.rooms.get(sa.code);r.startAt=Date.now()-r.items[0].target;wait=event(a,'state',d=>d.phase==='review');a.emit('answer',{roundKey:sa.roundKey,elapsed:999999});b.emit('answer',{roundKey:sa.roundKey,elapsed:999999});const result=await wait;assert.ok(result.result.results.every(x=>x.points>95));});
test('resume restores submitted choice; full departure returns surviving player to usable lobby',async t=>{const {connect}=await setup(t),{a,b,session,sa}=await room(connect,'telepathy');let wait=event(a,'state',d=>d.submitted);a.emit('answer',{roundKey:sa.roundKey,own:1,predict:1});await wait;a.disconnect();const c=await connect();wait=event(c,'state');c.emit('resume',{token:session.token});assert.equal((await wait).submitted,true);wait=event(b,'state',d=>d.phase==='lobby'&&d.host);c.emit('leave',{});assert.equal((await wait).players.length,1);});
test('timeout reveals, review advances, and third player cannot enter',async t=>{const {connect}=await setup(t,{roundMs:100,reviewMs:100}),{a,sa}=await room(connect,'telepathy'),c=await connect();let wait=event(c,'error-message');c.emit('join',{code:sa.code});await wait;const result=await event(a,'state',d=>d.phase==='review');assert.ok(result.result.results.every(x=>x.points===0));assert.equal((await event(a,'state',d=>d.phase==='round')).round,2);});
