'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const {bank,games}=require('../korean-data'),{prepare,grade}=require('../korean-server');
function setup(t){const handlers={},emitted=[];const socket={connected:true,on(e,fn){handlers[e]=fn;},emit(e,d){emitted.push({e,d});}};const dom=new JSDOM(fs.readFileSync('public/korean/index.html','utf8'),{url:'https://example.com/korean/',runScripts:'outside-only'});dom.window.io=()=>socket;dom.window.eval(fs.readFileSync('public/korean/korean.js','utf8'));handlers.catalog({games});t.after(()=>dom.window.close());return{window:dom.window,doc:dom.window.document,handlers,emitted};}
function state(q,phase='question'){return{runId:'test',roundKey:q.id,game:q.kind,mode:'solo',level:4,phase,round:1,total:5,code:'K123456',you:'p',host:true,players:[{id:'p',name:'<script>test</script>',connected:true,score:0,combo:0,hp:3}],deadline:Date.now()+50000,now:Date.now(),question:Object.fromEntries(Object.entries(q).filter(([k])=>!['answer','ja','explanation','similar','accepted'].includes(k))),submitted:false,done:0,ready:false,bossLeft:5,bossMax:5};}
test('all five interaction types submit answers accepted by server, Korean-first, safe names',t=>{const {doc,handlers,emitted}=setup(t);for(const kind of Object.keys(games).filter(x=>!['boss','memory','search','detective'].includes(x))){const q=prepare(bank.find(q=>q.kind===kind&&q.level===4));handlers.state(state(q));assert.equal(doc.querySelector('#surface').textContent.includes(q.ja),false);assert.equal(doc.querySelector('#players script'),null);if(kind==='sniper')doc.querySelectorAll('#surface .ko-option')[q.answer].click();if(kind==='nuance'){doc.querySelectorAll('.ko-pair').forEach((row,i)=>row.querySelectorAll('button')[q.answer[i]].click());doc.querySelector('#surface > .btn.primary').click();}if(kind==='order'){for(const i of q.answer)[...doc.querySelectorAll('.ko-tray button')].find(b=>b.textContent===q.cards[i]).click();doc.querySelector('#surface > .btn.primary').click();}if(kind==='repair'){doc.querySelectorAll('.ko-tray button')[q.answer.index].click();doc.querySelector('#surface input').value=q.answer.text;doc.querySelector('#surface form').dispatchEvent(new doc.defaultView.Event('submit',{bubbles:true,cancelable:true}));}if(kind==='survival'){doc.querySelector('#surface input').value=q.answer;doc.querySelector('#surface form').dispatchEvent(new doc.defaultView.Event('submit',{bubbles:true,cancelable:true}));}const last=emitted.filter(x=>x.e==='answer').at(-1);assert.equal(last.d.roundKey,q.id);assert.ok(grade(q,last.d.answer),kind);handlers.state({...state(q),submitted:true});assert.ok([...doc.querySelector('#surface').querySelectorAll('button,input')].every(x=>x.disabled));}});
test('review records are deduplicated, Japanese help is closed, weakness review emits only mistakes',t=>{const {doc,window,handlers,emitted}=setup(t),q=prepare(bank.find(x=>x.kind==='sniper'));const d={...state(q,'review'),review:{question:q,results:[{id:'p',name:'p',correct:false,points:0,answer:null}]}};handlers.state(d);handlers.state(d);const saved=JSON.parse(window.localStorage.getItem('korean-history-v1'));assert.equal(saved.answers.length,1);assert.equal(doc.querySelector('details').open,false);handlers.left();doc.querySelector('#weakness').click();const last=emitted.at(-1);assert.equal(last.e,'create');assert.equal(last.d.mode,'solo');assert.deepEqual([...last.d.review],[q.id]);});
test('home keeps all six original cards and links nine independent Korean game cards',()=>{const doc=new JSDOM(fs.readFileSync('public/index.html','utf8')).window.document;assert.equal(doc.querySelectorAll('[data-game]').length,6);assert.equal(doc.querySelectorAll('a[href^="/korean/?game="]').length,9);});
test('memory flip and search endpoints emit valid server moves and progress rerenders',t=>{
 const {doc,handlers,emitted}=setup(t),puzzles=require('../korean-puzzles');
 for(const kind of ['memory','search']){const q=prepare(bank.find(q=>q.kind===kind)),p=puzzles.progress();let d={...state(q),question:puzzles.publicQuestion(q,p)};handlers.state(d);
 if(kind==='memory'){doc.getElementById('memory-0').click();const move=emitted.at(-1);assert.equal(move.e,'puzzle-move');puzzles.move(q,p,move.d);handlers.state({...d,question:puzzles.publicQuestion(q,p)});assert.ok(doc.getElementById('memory-0').textContent.includes(q.tiles[0].text));}
 else{const path=q.answer[0];doc.getElementById(`letter-${path[0]}`).click();doc.getElementById(`letter-${path.at(-1)}`).click();const move=emitted.at(-1);assert.equal(move.e,'puzzle-move');assert.ok(puzzles.move(q,p,move.d));assert.deepEqual(p.found,[0]);handlers.state({...d,question:puzzles.publicQuestion(q,p)});assert.equal(doc.querySelectorAll('.ko-letter.found').length,path.length);}
 }
});
test('detective requires three stages, restores draft, and submits selected evidence',t=>{
 const {doc,window,handlers,emitted}=setup(t),q=prepare(bank.find(x=>x.kind==='detective'&&x.level===5)),d=state(q);
 handlers.state(d);assert.equal(doc.querySelectorAll('.ko-case-steps button')[1].disabled,true);
 doc.querySelectorAll('.ko-case-options button')[q.answer.choice].click();doc.querySelector('.ko-case-mission > .btn.primary').click();
 q.answer.evidence.forEach(i=>doc.querySelectorAll('.ko-evidence')[i].click());
 doc.querySelector('.ko-case-mission > .btn.primary').click();doc.querySelectorAll('.ko-case-options button')[q.answer.reason].click();
 const draft=JSON.parse(window.sessionStorage.getItem(`detective:${d.runId}:${d.roundKey}`));assert.equal(draft.step,2);assert.equal(draft.draft.evidence.length,2);
 handlers.state({...d,roundKey:'temporary'});handlers.state(d);assert.ok(doc.querySelector('.ko-case-mission').textContent.includes('이 보기는 왜 틀렸을까요?'));
 doc.querySelector('.ko-case-mission > .btn.primary').click();const sent=emitted.filter(x=>x.e==='answer').at(-1);assert.ok(grade(q,sent.d.answer));
 handlers.state({...d,phase:'review',review:{question:q,results:[{id:'p',name:'p',correct:true,points:100,answer:sent.d.answer}]}});
 assert.ok(doc.querySelector('#surface').textContent.includes('✓ 판단 · ✓ 근거 · ✓ 함정'));
});
