'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {Server}=require('socket.io'),{io:client}=require('socket.io-client');
const install=require('../korean-server'),{bank,games}=require('../korean-data');
const {grade,prepare,selectBank}=install;
function event(s,name,predicate=()=>true){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{s.off(name,fn);reject(new Error(`Timeout: ${name}`));},2000);function fn(d){if(predicate(d)){clearTimeout(timer);s.off(name,fn);resolve(d);}}s.on(name,fn);});}
async function setup(t,options={}){const server=http.createServer(),io=new Server(server),engine=install(io,{questionMs:800,reviewMs:800,grace:200,...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));const clients=[];t.after(async()=>{clients.forEach(s=>s.disconnect());engine.close();await new Promise(r=>io.close(r));});async function connect(){const s=client(`http://127.0.0.1:${server.address().port}/korean`,{transports:['websocket'],forceNew:true,reconnection:false});clients.push(s);await event(s,'connect');return s;}return{connect,engine};}
async function create(s,data={}){const session=event(s,'session'),state=event(s,'state',d=>d.phase===(data.mode&&data.mode!=='solo'?'lobby':'question'));s.emit('create',{game:'sniper',mode:'solo',level:4,count:5,...data});return{session:await session,state:await state};}
function answerFor(engine,state){return engine.rooms.get(state.code).items[state.round-1].answer;}
test('content schema, all five levels, answer shuffling and normalized Korean input',()=>{assert.equal(new Set(bank.map(q=>q.id)).size,bank.length);for(const q of bank){assert.ok(q.ja&&q.explanation&&q.similar);assert.ok(q.level>=1&&q.level<=5);for(let i=0;i<5;i++){const p=prepare(q);assert.ok(grade(p,p.answer),q.id);assert.ok(!grade(p,null),q.id);if(q.options)assert.equal(new Set(q.options).size,q.options.length);}}for(const g of Object.keys(games))for(let level=1;level<=5;level++)assert.ok(selectBank(g,level).length);const word=bank.find(q=>q.kind==='survival');assert.ok(grade(word,word.answer.normalize('NFD')+' '));const spelling=bank.find(q=>q.id==='repair-2');assert.ok(grade(spelling,{index:1,text:'뵈어요'}));});
test('solo can complete every game; no answers leak before reveal; stale events cannot advance next round',async t=>{const {connect,engine}=await setup(t,{questionMs:10000,reviewMs:10000});const s=await connect();for(const game of Object.keys(games)){let {state}=await create(s,{game});const ids=new Set();for(let i=0;i<state.total;i++){assert.equal(state.phase,'question');assert.ok(!('answer' in state.question));assert.ok(!('ja' in state.question));assert.ok(!ids.has(state.question.id));ids.add(state.question.id);const key=state.roundKey;const result=event(s,'state',x=>x.phase==='review');const q=engine.rooms.get(state.code).items[state.round-1];if(q.kind==='memory'){for(let pair=0;pair<q.pairs.length;pair++)q.tiles.forEach((tile,index)=>{if(tile.pair===pair)s.emit('puzzle-move',{roundKey:key,index});});}else if(q.kind==='search'){q.answer.forEach((path,clue)=>s.emit('puzzle-move',{roundKey:key,clue,path}));}else s.emit('answer',{roundKey:key,answer:answerFor(engine,state)});s.emit('answer',{roundKey:key,answer:null});state=await result;assert.ok(state.review.results[0].correct);const next=event(s,'state',x=>x.phase==='question'||x.phase==='finished');s.emit('ready',{roundKey:key});state=await next;s.emit('answer',{roundKey:key,answer:0});s.emit('ready',{roundKey:key});}assert.equal(state.phase,'finished');assert.equal(state.summary.length,state.total);assert.ok(state.summary.every(x=>x.correct));const left=event(s,'left');s.emit('leave',{});await left;}});
test('VS waits for everyone, reconnect preserves locked submission, host departure transfers control',async t=>{const {connect,engine}=await setup(t,{questionMs:10000,reviewMs:10000,grace:200});const a=await connect(),b=await connect();const room=await create(a,{mode:'vs'});const joined=event(b,'state');b.emit('join',{code:room.state.code,name:'B'});await joined;const qa=event(a,'state',s=>s.phase==='question'),qb=event(b,'state',s=>s.phase==='question');a.emit('start',{});const first=await qa;await qb;const locked=event(a,'state',x=>x.submitted);a.emit('answer',{roundKey:first.roundKey,answer:answerFor(engine,first)});await locked;a.disconnect();const replacement=await connect();const resumed=event(replacement,'state');replacement.emit('resume',{token:room.session.token});const rs=await resumed;assert.ok(rs.submitted);assert.equal(rs.you,first.you);assert.equal(rs.roundKey,first.roundKey);const review=event(replacement,'state',x=>x.phase==='review');b.emit('answer',{roundKey:first.roundKey,answer:answerFor(engine,first)});await review;const hostChanged=event(b,'state',x=>x.host);replacement.emit('leave',{});assert.ok((await hostChanged).host);const next=event(b,'state',x=>x.phase==='question');b.emit('ready',{roundKey:first.roundKey});await next;});
test('question timeout, review timeout and all-disconnected resume cannot strand a round',async t=>{const {connect}=await setup(t,{questionMs:100,reviewMs:100,grace:1000});const a=await connect(),created=await create(a);const timeout=await event(a,'state',s=>s.phase==='review');assert.equal(timeout.review.results[0].correct,false);const next=await event(a,'state',s=>s.phase==='question');assert.equal(next.round,2);a.disconnect();await new Promise(r=>setTimeout(r,250));const b=await connect(),resume=event(b,'state');b.emit('resume',{token:created.session.token});const restored=await resume;assert.equal(restored.phase,'question');assert.equal(restored.round,3);assert.ok(restored.deadline>restored.now);});
test('CO-OP shares damage and minimum start count; outsiders and malformed payloads cannot mutate rooms',async t=>{const {connect,engine}=await setup(t,{questionMs:10000});const a=await connect(),b=await connect(),outsider=await connect();const {state}=await create(a,{mode:'coop'});const insufficient=event(a,'error-message');a.emit('start',{});await insufficient;const joined=event(b,'state');b.emit('join',{code:state.code});await joined;const started=event(a,'state',x=>x.phase==='question');a.emit('start',{});const first=await started;outsider.emit('answer',{roundKey:first.roundKey,answer:0});outsider.emit('answer',null);outsider.emit('ready',null);const result=event(a,'state',x=>x.phase==='review');a.emit('answer',{roundKey:first.roundKey,answer:answerFor(engine,first)});b.emit('answer',{roundKey:first.roundKey,answer:-1});const d=await result;assert.equal(d.teamHp,4);assert.equal(d.review.results.length,2);assert.equal(d.review.results.filter(x=>x.correct).length,1);});
test('survival ends at zero HP and review targets only requested mistakes',async t=>{const {connect}=await setup(t,{questionMs:10000});const a=await connect();let {state}=await create(a,{game:'survival'});for(let i=0;i<3;i++){const reveal=event(a,'state',x=>x.phase==='review');a.emit('answer',{roundKey:state.roundKey,answer:'틀린 답'});state=await reveal;const next=event(a,'state',x=>x.phase!=='review');a.emit('ready',{roundKey:state.roundKey});state=await next;}assert.equal(state.phase,'finished');assert.equal(state.players[0].hp,0);const ids=['sniper-1','repair-12'];assert.deepEqual(new Set(selectBank('boss',5,ids).map(x=>x.id)),new Set(ids));});
test('memory hides other cards, rejects direct answer bypass, and resumes a flipped card',async t=>{
 const {connect,engine}=await setup(t,{questionMs:10000,grace:1000});const a=await connect();const created=await create(a,{game:'memory'}),d=created.state;
 assert.ok(d.question.tiles.every(x=>x.text===null));assert.ok(!('pairs' in d.question));a.emit('answer',{roundKey:d.roundKey,answer:answerFor(engine,d)});
 let pending=event(a,'state',x=>x.question?.tiles[0].text);a.emit('puzzle-move',{roundKey:d.roundKey,index:0});const shown=await pending;assert.equal(shown.question.tiles.filter(x=>x.text!==null).length,1);assert.equal(shown.submitted,false);
 a.disconnect();const b=await connect();pending=event(b,'state');b.emit('resume',{token:created.session.token});const restored=await pending;assert.equal(restored.question.tiles[0].text,shown.question.tiles[0].text);
});
test('both puzzle types work in VS and CO-OP without revealing before both players finish',async t=>{
 const {connect,engine}=await setup(t,{questionMs:10000});for(const game of ['memory','search'])for(const mode of ['vs','coop']){
  const a=await connect(),b=await connect(),created=await create(a,{game,mode});let pending=event(b,'state');b.emit('join',{code:created.state.code});await pending;pending=event(a,'state',d=>d.phase==='question');a.emit('start',{});const d=await pending,q=engine.rooms.get(d.code).items[0];
  function solve(s){if(game==='memory'){for(let pair=0;pair<q.pairs.length;pair++)q.tiles.forEach((v,index)=>{if(v.pair===pair)s.emit('puzzle-move',{roundKey:d.roundKey,index});});}else q.answer.forEach((path,clue)=>s.emit('puzzle-move',{roundKey:d.roundKey,clue,path}));}
  pending=event(a,'state',x=>x.submitted);solve(a);assert.equal((await pending).phase,'question');pending=event(a,'state',x=>x.phase==='review');solve(b);const result=await pending;assert.ok(result.review.results.every(x=>x.correct));assert.equal(result.teamHp,5);a.emit('leave',{});b.emit('leave',{});
 }
});
