const express = require('express');
const http = require('http');
const path = require('path');
const { Server } = require('socket.io');
const { genshinQuestions, valuePrompts, oneLinerPrompts, wordPairs, titleScenes } = require('./questions');

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
  cors: { origin: true, credentials: false },
  connectionStateRecovery: { maxDisconnectionDuration: 2 * 60 * 1000, skipMiddlewares: true }
});

const GAMES = {
  genshin: { title:'原神クイズ', category:'知識系', icon:'✦', min:1, max:40, rounds:[5,10,15,20], defaultRounds:10, seconds:[10,15,20,30], defaultSeconds:15 },
  values: { title:'価値観一致', category:'パーティー系', icon:'🧠', min:2, max:20, rounds:[5,8,10,12], defaultRounds:8, seconds:[15,20,30], defaultSeconds:20 },
  oneLiner: { title:'お題で一言', category:'パーティー系', icon:'💬', min:3, max:12, rounds:[5,8,10,12], defaultRounds:8, seconds:[20,30,45,60], defaultSeconds:35 },
  wordWolf: { title:'ワードウルフ', category:'正体隠匿系', icon:'🐺', min:3, max:20, rounds:[3,5,8,10], defaultRounds:5, seconds:[30,45,60,90], defaultSeconds:60 },
  werewolf4: { title:'4人ミニ人狼', category:'正体隠匿系', icon:'🌙', min:4, max:4, exact:4, rounds:[1], defaultRounds:1, seconds:[60,90,120,180], defaultSeconds:90 },
  title: { title:'タイトル学園', category:'大喜利系', icon:'📷', min:3, max:12, rounds:[5,8,10,12], defaultRounds:8, seconds:[20,30,35,45,60], defaultSeconds:35 }
};

app.use(express.static(path.join(__dirname, 'public')));
app.get('/health', (_, res) => res.json({ ok: true, games: Object.keys(GAMES) }));

const rooms = new Map();
const pendingDisconnects = new Map();
const ROOM_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const DISCONNECT_GRACE_MS = 30000;

function makeCode(){for(let t=0;t<100;t++){let c='';for(let i=0;i<5;i++)c+=ROOM_CHARS[Math.floor(Math.random()*ROOM_CHARS.length)];if(!rooms.has(c))return c;}return Math.random().toString(36).slice(2,8).toUpperCase();}
function safeName(v){return String(v||'').trim().slice(0,18)||'プレイヤー';}
function safeText(v){return String(v||'').trim().replace(/\s+/g,' ').slice(0,80);}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function clearTimer(room){if(room.timer)clearTimeout(room.timer);room.timer=null;room.phaseEndsAt=0;}
function setTimer(room,seconds,fn){clearTimer(room);room.phaseEndsAt=Date.now()+seconds*1000;room.timer=setTimeout(fn,seconds*1000);}
function publicPlayers(room){return [...room.players.values()].map(p=>({id:p.id,name:p.name,score:p.score,isHost:p.id===room.hostId})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'ja'));}
function gameMeta(game){return GAMES[game]||GAMES.values;}
function lobbyState(room){const m=gameMeta(room.game);return{code:room.code,game:room.game,gameTitle:m.title,category:m.category,icon:m.icon,status:room.status,phase:room.phase,rounds:room.rounds,seconds:room.seconds,settings:{rounds:m.rounds,seconds:m.seconds,min:m.min,max:m.max,exact:m.exact||null},players:publicPlayers(room)};}
function emitLobby(room){io.to(room.code).emit('lobby-state',lobbyState(room));}
function roundInfo(room){return room.game==='werewolf4'?{round:1,total:1}:{round:room.roundIndex+1,total:room.playItems.length};}
function minPlayersOk(room){const m=gameMeta(room.game);return m.exact?room.players.size===m.exact:room.players.size>=m.min;}
function abortToLobby(room,message){clearTimer(room);room.status='lobby';room.phase='lobby';room.roundIndex=0;room.playItems=[];room.responses=new Map();room.submissions=new Map();room.entries=[];room.votes=new Map();room.lastResult=null;room.wolfId=null;room.seerId=null;room.seerResult=null;room.voteCandidates=[];room.voteHistory=[];for(const p of room.players.values())p.role=null;io.to(room.code).emit('game-aborted',message);emitLobby(room);}
function finishStandard(room){clearTimer(room);room.status='finished';room.phase='finished';io.to(room.code).emit('game-finished',{game:room.game,players:publicPlayers(room)});emitLobby(room);}
function nextRound(room,delay=5500){clearTimer(room);room.timer=setTimeout(()=>{if(!rooms.has(room.code)||room.status!=='playing'||room.phase!=='result')return;room.roundIndex++;if(room.roundIndex>=room.playItems.length)finishStandard(room);else startCurrentRound(room);},delay);}

function prepareQuizQuestion(q){const pairs=q.options.map((text,i)=>({text,ko:q.optionsKo?.[i]||'',correct:i===q.answer}));const mixed=shuffle(pairs);return{text:q.text,ko:q.ko||'',options:mixed.map(x=>x.text),optionsKo:mixed.map(x=>x.ko),answer:mixed.findIndex(x=>x.correct)};}
function startChoiceRound(room){room.phase='choice';room.responses=new Map();room.lastResult=null;const item=room.playItems[room.roundIndex];const payload=room.game==='genshin'?{...roundInfo(room),kind:'quiz',text:item.text,ko:item.ko,options:item.options,optionsKo:item.optionsKo,seconds:room.seconds}:{...roundInfo(room),kind:'values',text:item.text,options:item.options,seconds:room.seconds};io.to(room.code).emit('choice-round',payload);io.to(room.code).emit('answer-progress',{done:0,total:room.players.size});setTimer(room,room.seconds,()=>revealChoice(room));}
function revealChoice(room){if(!rooms.has(room.code)||room.status!=='playing'||room.phase!=='choice')return;clearTimer(room);room.phase='result';const item=room.playItems[room.roundIndex],counts=[0,0,0,0],voters=[[],[],[],[]];for(const p of room.players.values()){const pick=room.responses.get(p.id);if(Number.isInteger(pick)&&pick>=0&&pick<4){counts[pick]++;voters[pick].push(p.name);}}let payload;if(room.game==='genshin'){for(const p of room.players.values())if(room.responses.get(p.id)===item.answer)p.score+=500;payload={...roundInfo(room),kind:'quiz',text:item.text,ko:item.ko,options:item.options,optionsKo:item.optionsKo,counts,voters,correctIndex:item.answer,players:publicPlayers(room)};}else{const max=Math.max(...counts),winners=max>0?counts.map((n,i)=>n===max?i:-1).filter(i=>i>=0):[];for(const p of room.players.values())if(winners.includes(room.responses.get(p.id)))p.score+=500;payload={...roundInfo(room),kind:'values',text:item.text,options:item.options,counts,voters,winners,players:publicPlayers(room)};}room.lastResult={event:'choice-result',payload};io.to(room.code).emit('choice-result',payload);nextRound(room,6000);}

function textItemPayload(room){const item=room.playItems[room.roundIndex];return room.game==='title'?{scene:item}:{prompt:item};}
function startTextRound(room){room.phase='writing';room.submissions=new Map();room.entries=[];room.votes=new Map();room.lastResult=null;io.to(room.code).emit('text-round',{...roundInfo(room),kind:room.game,...textItemPayload(room),seconds:room.seconds});io.to(room.code).emit('answer-progress',{done:0,total:room.players.size});setTimer(room,room.seconds,()=>beginTextVoting(room));}
function textEligible(room){return[...room.players.keys()].filter(id=>room.entries.some(e=>e.authorId!==id));}
function beginTextVoting(room){if(!rooms.has(room.code)||room.status!=='playing'||room.phase!=='writing')return;clearTimer(room);room.entries=shuffle([...room.submissions.entries()].filter(([id,text])=>room.players.has(id)&&text).map(([authorId,text])=>({id:Math.random().toString(36).slice(2,10),authorId,text})));room.votes=new Map();if(room.entries.length<2)return revealText(room,true);room.phase='text-voting';for(const p of room.players.values())io.to(p.id).emit('text-voting',{...roundInfo(room),kind:room.game,...textItemPayload(room),seconds:20,submissions:room.entries.map(e=>({id:e.id,text:e.text,mine:e.authorId===p.id}))});const eligible=textEligible(room);io.to(room.code).emit('vote-progress',{voted:0,total:eligible.length});if(!eligible.length)return revealText(room,true);setTimer(room,20,()=>revealText(room));}
function revealText(room,noContest=false){if(!rooms.has(room.code)||room.status!=='playing'||!['writing','text-voting'].includes(room.phase))return;clearTimer(room);room.phase='result';const voteCounts=new Map(room.entries.map(e=>[e.id,0]));for(const id of room.votes.values())if(voteCounts.has(id))voteCounts.set(id,voteCounts.get(id)+1);const max=Math.max(0,...voteCounts.values()),winnerIds=!noContest&&max>0?[...voteCounts.entries()].filter(([,n])=>n===max).map(([id])=>id):[];if(!noContest)for(const e of room.entries){const p=room.players.get(e.authorId);if(!p)continue;p.score+=(voteCounts.get(e.id)||0)*200;if(winnerIds.includes(e.id))p.score+=500;}const entries=room.entries.map(e=>({id:e.id,text:e.text,authorName:room.players.get(e.authorId)?.name||'退出した人',votes:voteCounts.get(e.id)||0,winner:winnerIds.includes(e.id)})).sort((a,b)=>b.votes-a.votes||a.authorName.localeCompare(b.authorName,'ja'));const payload={...roundInfo(room),kind:room.game,...textItemPayload(room),entries,players:publicPlayers(room),message:noContest?'回答が2つ未満だったのでノーコンテスト。':winnerIds.length>1?'同票優勝！':winnerIds.length===1?'最多得票が今ラウンドの優勝！':'今回は投票なし。'};room.lastResult={event:'text-result',payload};io.to(room.code).emit('text-result',payload);nextRound(room,6500);}

function startWordWolfRound(room){if(room.players.size<3)return abortToLobby(room,'3人未満になったためゲームを中断しました。');room.phase='discussion';room.votes=new Map();room.lastResult=null;const pair=room.playItems[room.roundIndex],ids=[...room.players.keys()];room.wolfId=ids[Math.floor(Math.random()*ids.length)];const swap=Math.random()<.5;room.majorityWord=swap?pair.b:pair.a;room.minorityWord=swap?pair.a:pair.b;io.to(room.code).emit('word-round',{...roundInfo(room),seconds:room.seconds,players:publicPlayers(room)});for(const p of room.players.values())io.to(p.id).emit('word-secret',{word:p.id===room.wolfId?room.minorityWord:room.majorityWord});setTimer(room,room.seconds,()=>beginPlayerVoting(room,false));}
function beginPlayerVoting(room,revote=false,candidates=null){if(!rooms.has(room.code)||room.status!=='playing')return;clearTimer(room);room.votes=new Map();room.phase=room.game==='wordWolf'?'player-voting':revote?'revoting':'player-voting';room.voteCandidates=candidates?.length?[...candidates]:[...room.players.keys()];io.to(room.code).emit('player-voting',{kind:room.game,...roundInfo(room),seconds:25,revote,players:publicPlayers(room),candidates:publicPlayers(room).filter(p=>room.voteCandidates.includes(p.id))});io.to(room.code).emit('vote-progress',{voted:0,total:room.players.size});setTimer(room,25,()=>room.game==='wordWolf'?revealWordWolf(room):resolveWerewolfVote(room));}
function revealWordWolf(room){if(!rooms.has(room.code)||room.status!=='playing'||room.phase!=='player-voting')return;clearTimer(room);room.phase='result';const counts=new Map([...room.players.keys()].map(id=>[id,0])),voters=new Map([...room.players.keys()].map(id=>[id,[]]));for(const[voterId,targetId]of room.votes.entries())if(counts.has(targetId)&&room.players.has(voterId)){counts.set(targetId,counts.get(targetId)+1);voters.get(targetId).push(room.players.get(voterId).name);}const max=Math.max(0,...counts.values()),topIds=max>0?[...counts.entries()].filter(([,n])=>n===max).map(([id])=>id):[],caught=topIds.length===1&&topIds[0]===room.wolfId;if(caught){for(const[voterId,targetId]of room.votes.entries())if(targetId===room.wolfId&&room.players.has(voterId))room.players.get(voterId).score+=400;}else if(room.players.has(room.wolfId))room.players.get(room.wolfId).score+=700;const results=publicPlayers(room).map(p=>({...p,votes:counts.get(p.id)||0,voters:voters.get(p.id)||[],isMinority:p.id===room.wolfId})).sort((a,b)=>b.votes-a.votes);const payload={...roundInfo(room),caught,minorityName:room.players.get(room.wolfId)?.name||'退出した人',majorityWord:room.majorityWord,minorityWord:room.minorityWord,voteResults:results,players:publicPlayers(room)};room.lastResult={event:'word-result',payload};io.to(room.code).emit('word-result',payload);nextRound(room,7500);}

function roleLabel(role){return role==='wolf'?'人狼':role==='seer'?'占い師':'村人';}
function startWerewolf(room){const roles=shuffle(['wolf','seer','villager','villager']),players=[...room.players.values()];players.forEach((p,i)=>{p.role=roles[i];if(p.role==='wolf')room.wolfId=p.id;if(p.role==='seer')room.seerId=p.id;});room.status='playing';room.phase='seer';room.seerResult=null;room.votes=new Map();room.voteCandidates=[];room.voteHistory=[];io.to(room.code).emit('game-started',{game:room.game,gameTitle:GAMES[room.game].title,total:1});for(const p of players){io.to(p.id).emit('role-info',{role:p.role,roleLabel:roleLabel(p.role)});io.to(p.id).emit('seer-phase',{isSeer:p.role==='seer',targets:p.role==='seer'?publicPlayers(room).filter(x=>x.id!==p.id):[],seconds:20});}setTimer(room,20,()=>beginWerewolfDiscussion(room));}
function beginWerewolfDiscussion(room){if(!rooms.has(room.code)||room.status!=='playing'||room.phase!=='seer')return;room.phase='discussion';io.to(room.code).emit('werewolf-discussion',{seconds:room.seconds,players:publicPlayers(room)});setTimer(room,room.seconds,()=>beginPlayerVoting(room,false));}
function resolveWerewolfVote(room){if(!rooms.has(room.code)||room.status!=='playing'||!['player-voting','revoting'].includes(room.phase))return;const wasRevote=room.phase==='revoting';clearTimer(room);const counts=new Map(room.voteCandidates.map(id=>[id,0])),voters=new Map(room.voteCandidates.map(id=>[id,[]]));for(const[voterId,targetId]of room.votes.entries())if(counts.has(targetId)&&room.players.has(voterId)){counts.set(targetId,counts.get(targetId)+1);voters.get(targetId).push(room.players.get(voterId).name);}const max=Math.max(0,...counts.values()),topIds=max>0?[...counts.entries()].filter(([,n])=>n===max).map(([id])=>id):[];room.voteHistory.push({revote:wasRevote,results:room.voteCandidates.map(id=>({id,name:room.players.get(id)?.name||'退出した人',votes:counts.get(id)||0,voters:voters.get(id)||[]}))});if(!wasRevote&&topIds.length>1){room.phase='tie';io.to(room.code).emit('werewolf-tie',{candidates:publicPlayers(room).filter(p=>topIds.includes(p.id))});room.timer=setTimeout(()=>{if(rooms.has(room.code)&&room.status==='playing'&&room.phase==='tie')beginPlayerVoting(room,true,topIds);},2200);return;}const executedId=topIds.length===1?topIds[0]:null,villageWin=executedId===room.wolfId;finishWerewolf(room,{villageWin,executedId,finalTie:wasRevote&&topIds.length!==1,noVotes:topIds.length===0});}
function finishWerewolf(room,outcome){clearTimer(room);room.status='finished';room.phase='finished';const roles=[...room.players.values()].map(p=>({id:p.id,name:p.name,role:p.role,roleLabel:roleLabel(p.role)})),result={...outcome,wolfName:room.players.get(room.wolfId)?.name||'不明',roles,voteHistory:room.voteHistory};io.to(room.code).emit('game-finished',{game:room.game,players:publicPlayers(room),werewolf:result});emitLobby(room);}

function sourceFor(game){if(game==='genshin')return genshinQuestions;if(game==='values')return valuePrompts;if(game==='oneLiner')return oneLinerPrompts;if(game==='wordWolf')return wordPairs;if(game==='title')return titleScenes;return[];}
function startCurrentRound(room){if(!rooms.has(room.code)||room.status!=='playing')return;if(!minPlayersOk(room))return abortToLobby(room,'必要な人数がそろわなくなったためゲームを中断しました。');if(room.game==='genshin'||room.game==='values')return startChoiceRound(room);if(room.game==='oneLiner'||room.game==='title')return startTextRound(room);if(room.game==='wordWolf')return startWordWolfRound(room);}
function startGame(room){const meta=gameMeta(room.game);if(meta.exact?room.players.size!==meta.exact:room.players.size<meta.min)return io.to(room.hostId).emit('input-error',meta.exact?`${meta.exact}人ちょうどで開始できます！`:`${meta.min}人以上で開始できます！`);for(const p of room.players.values()){p.score=0;p.role=null;}if(room.game==='werewolf4')return startWerewolf(room);const src=sourceFor(room.game);room.playItems=shuffle(src).slice(0,Math.min(room.rounds,src.length));if(room.game==='genshin')room.playItems=room.playItems.map(prepareQuizQuestion);room.roundIndex=0;room.status='playing';room.phase='starting';io.to(room.code).emit('game-started',{game:room.game,gameTitle:meta.title,total:room.playItems.length});emitLobby(room);setTimeout(()=>{if(rooms.has(room.code)&&room.status==='playing')startCurrentRound(room);},700);}
function checkCompletion(room){if(room.status!=='playing')return;if(room.phase==='choice'&&room.responses.size>=room.players.size)setTimeout(()=>revealChoice(room),300);if(room.phase==='writing'&&room.submissions.size>=room.players.size)setTimeout(()=>beginTextVoting(room),300);if(room.phase==='text-voting'){const eligible=textEligible(room),voted=eligible.filter(id=>room.votes.has(id)).length;io.to(room.code).emit('vote-progress',{voted,total:eligible.length});if(voted>=eligible.length)setTimeout(()=>revealText(room),300);}if(room.phase==='player-voting'||room.phase==='revoting'){io.to(room.code).emit('vote-progress',{voted:room.votes.size,total:room.players.size});if(room.votes.size>=room.players.size)setTimeout(()=>room.game==='wordWolf'?revealWordWolf(room):resolveWerewolfVote(room),300);}}
function cleanupDisconnectedPlayer(code,id){const room=rooms.get(code);if(!room||!room.players.has(id))return;if(room.hostId===id){clearTimer(room);io.to(code).emit('room-closed','ホストが退出したため、ルームが終了しました。');rooms.delete(code);return;}const critical=room.status==='playing'&&(room.game==='werewolf4'||(room.game==='wordWolf'&&room.wolfId===id));room.players.delete(id);room.responses.delete(id);room.submissions.delete(id);room.votes.delete(id);const removed=room.entries.filter(e=>e.authorId===id).map(e=>e.id);room.entries=room.entries.filter(e=>e.authorId!==id);for(const[voter,target]of[...room.votes.entries()])if(target===id||removed.includes(target))room.votes.delete(voter);if(critical)return abortToLobby(room,'重要な役割のプレイヤーが退出したためゲームを中断しました。');if(room.status==='playing'&&!minPlayersOk(room))return abortToLobby(room,'必要な人数がそろわなくなったためゲームを中断しました。');emitLobby(room);checkCompletion(room);}

io.on('connection',socket=>{
  if(socket.recovered){const pending=pendingDisconnects.get(socket.id);if(pending){clearTimeout(pending);pendingDisconnects.delete(socket.id);}const room=rooms.get(socket.data.roomCode);if(room)emitLobby(room);}
  socket.on('create-room',({name,game})=>{game=GAMES[game]?game:'values';const meta=gameMeta(game),code=makeCode(),room={code,hostId:socket.id,game,status:'lobby',phase:'lobby',rounds:meta.defaultRounds,seconds:meta.defaultSeconds,players:new Map(),playItems:[],roundIndex:0,responses:new Map(),submissions:new Map(),entries:[],votes:new Map(),timer:null,phaseEndsAt:0,lastResult:null,wolfId:null,seerId:null,seerResult:null,voteCandidates:[],voteHistory:[]};room.players.set(socket.id,{id:socket.id,name:safeName(name),score:0,role:null});rooms.set(code,room);socket.join(code);socket.data.roomCode=code;socket.emit('room-created',{code,isHost:true,game});emitLobby(room);});
  socket.on('join-room',({code,name})=>{code=String(code||'').trim().toUpperCase();const room=rooms.get(code);if(!room)return socket.emit('join-error','そのルームは見つかりません。');if(room.status!=='lobby')return socket.emit('join-error','このルームはすでにゲーム中です。');const meta=gameMeta(room.game);if(room.players.size>=meta.max)return socket.emit('join-error','このルームは満員です。');room.players.set(socket.id,{id:socket.id,name:safeName(name),score:0,role:null});socket.join(code);socket.data.roomCode=code;socket.emit('room-joined',{code,isHost:false,game:room.game});emitLobby(room);});
  socket.on('update-settings',({code,rounds,seconds})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.hostId!==socket.id||room.status!=='lobby')return;const meta=gameMeta(room.game),r=Number(rounds),s=Number(seconds);if(meta.rounds.includes(r))room.rounds=r;if(meta.seconds.includes(s))room.seconds=s;emitLobby(room);});
  socket.on('start-game',({code})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.hostId!==socket.id||room.status!=='lobby')return;startGame(room);});
  socket.on('submit-choice',({code,choice})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.phase!=='choice'||room.responses.has(socket.id)||!room.players.has(socket.id))return;const n=Number(choice);if(!Number.isInteger(n)||n<0||n>3)return;room.responses.set(socket.id,n);socket.emit('submission-locked');io.to(room.code).emit('answer-progress',{done:room.responses.size,total:room.players.size});checkCompletion(room);});
  socket.on('submit-text',({code,text})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.phase!=='writing'||room.submissions.has(socket.id)||!room.players.has(socket.id))return;const cleaned=safeText(text);if(!cleaned)return socket.emit('input-error','一言を入力してね！');room.submissions.set(socket.id,cleaned);socket.emit('submission-locked');io.to(room.code).emit('answer-progress',{done:room.submissions.size,total:room.players.size});checkCompletion(room);});
  socket.on('submit-text-vote',({code,submissionId})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.phase!=='text-voting'||room.votes.has(socket.id))return;const target=room.entries.find(e=>e.id===String(submissionId));if(!target||target.authorId===socket.id)return;room.votes.set(socket.id,target.id);socket.emit('vote-locked');checkCompletion(room);});
  socket.on('force-vote',({code})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.hostId!==socket.id||room.status!=='playing'||room.phase!=='discussion')return;if(room.game==='wordWolf'||room.game==='werewolf4')beginPlayerVoting(room,false);});
  socket.on('submit-player-vote',({code,targetId})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||!['player-voting','revoting'].includes(room.phase)||room.votes.has(socket.id))return;targetId=String(targetId||'');if(!room.players.has(socket.id)||!room.voteCandidates.includes(targetId)||targetId===socket.id)return socket.emit('input-error','その人には投票できません。');room.votes.set(socket.id,targetId);socket.emit('vote-locked');checkCompletion(room);});
  socket.on('seer-check',({code,targetId})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.game!=='werewolf4'||room.phase!=='seer'||socket.id!==room.seerId||room.seerResult)return;targetId=String(targetId||'');if(!room.players.has(targetId)||targetId===socket.id)return;const target=room.players.get(targetId);room.seerResult={targetId,targetName:target.name,isWolf:target.role==='wolf'};socket.emit('seer-result',room.seerResult);});
  socket.on('restart-lobby',({code})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room||room.hostId!==socket.id||room.status!=='finished')return;clearTimer(room);room.status='lobby';room.phase='lobby';room.playItems=[];room.roundIndex=0;room.responses=new Map();room.submissions=new Map();room.entries=[];room.votes=new Map();room.lastResult=null;room.wolfId=null;room.seerId=null;room.seerResult=null;room.voteCandidates=[];room.voteHistory=[];for(const p of room.players.values()){p.score=0;p.role=null;}io.to(room.code).emit('back-to-lobby');emitLobby(room);});
  socket.on('disconnect',()=>{const code=socket.data.roomCode;if(!code||!rooms.has(code))return;const old=pendingDisconnects.get(socket.id);if(old)clearTimeout(old);const t=setTimeout(()=>{pendingDisconnects.delete(socket.id);cleanupDisconnectedPlayer(code,socket.id);},DISCONNECT_GRACE_MS);pendingDisconnects.set(socket.id,t);});
});

const PORT=process.env.PORT||3000;
server.listen(PORT,()=>console.log(`Minna Game Center running on port ${PORT}`));